# Generated by Django 5.2.3 on 2025-07-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(max_length=250)),
                ("line2", models.CharField(max_length=250)),
                ("subline", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("subtitle", models.CharField()),
                ("text", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="FillingText",
        ),
    ]
