# Generated by Django 5.2.3 on 2025-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_header_service_delete_fillingtext"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(default=None, upload_to="images"),
        ),
    ]
