# Generated by Django 5.2.3 on 2025-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0003_service_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "image",
                    models.ImageField(default=None, upload_to="images/materials"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="header",
            name="line2",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(default=None, upload_to="images/services"),
        ),
        migrations.AlterField(
            model_name="service",
            name="subtitle",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
