# Generated by Django 5.2.3 on 2025-07-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0004_materials_alter_header_line2_alter_service_image_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Materials",
            new_name="Material",
        ),
    ]
