# Generated by Django 5.2.3 on 2025-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0005_rename_materials_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=11)),
                ("button_text", models.CharField(max_length=250)),
                ("title", models.CharField(max_length=250)),
                ("subtitle", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(default=None, max_length=11)),
                ("text", models.CharField(default=None, max_length=250)),
                ("adress", models.CharField(default=None, max_length=250)),
                ("email", models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block1", models.CharField(max_length=250)),
                ("block2", models.CharField(max_length=250)),
                ("block3", models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name="header",
            name="line2",
        ),
    ]
