# Generated by Django 5.2.3 on 2025-07-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0006_contact_footer_navigation_remove_header_line2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footer",
            old_name="adress",
            new_name="address",
        ),
    ]
